### ISSUE TITLE
Add a comment section to your videos

### ISSUE THREAD

**Issue by nickmura** [CabbagePenetrator/gore.live#10]
Wanted to ask if your pancakes video was using maple syrup. Unfortunately I couldn't.

**Comment by CabbagePenetrator** [comment]
Hey Nickmura,

Adding comments/notifications next, going to start looking at it tomorrow.
Will comment here when it's done.

Thanks for the issue!

**Comment by CabbagePenetrator** [comment]
@nickmura Comments and notifications are live now! 🎉

**Comment by nickmura** [comment]
Nice!
