### ISSUE TITLE
what on earth is this

### ISSUE THREAD

**Issue by Parapass** [CabbagePenetrator/gore.live#2]

**Comment by CabbagePenetrator** [comment]
Hey Parapass!

It's a site that will feature videos of people getting badly hurt etc

**Comment by Parapass** [comment]
but why

**Comment by CabbagePenetrator** [comment]
because I don't like current gore sites, wanted to make my own

**Comment by Parapass** [comment]
why are you watching gore is my question

**Comment by CabbagePenetrator** [comment]
the media censors a lot of stuff, so it's nice to see what's actually happening in the world.
Also morbid curiosity.
